version: 0.2

env:
  variables:
    APP_NAME: spring-petclinic-

phases:
  install:
    commands:
     # variables
      #- REPOSITORY_URI=repository  
      #- ARTIFACT=spring-boot
      #- ARTIFACT_TYPE=.jar 
      #- TAG_NAME=$REPOSITORY_URI:$ARTIFACT
      #- echo $AWS_DEFAULT_REGION 
      #- echo $ARTIFACT
      #- echo $ARTIFACT_TYPE
      #- echo $REPOSITORY_URI
      #- echo $TAG_NAME  
      # installation
      - apt-get update -y
      - apt-get install -y software-properties-common
      #- apt-get install -y openjdk-11-jdk-headless
      - apt-get install -y default-jdk
      - apt-get install -y maven
      - apt-get install -y gradle

  pre_build:
    commands:

  build:
    commands:
      - echo Maven Build ...
      - if [ -e spring-petclinic ]; then cd spring-petclinic; fi
      - mvn package
      #- java -jar target/*.jar
      - echo $Env:CODEBUILD_BUILD_IMAGE
      - echo $Env:CODEBUILD_BUILD_ID
      - echo $Env:CODEBUILD_BUILD_NUMBER
      -
      - echo $Env:CODEBUILD_PUBLIC_BUILD_URL
      - echo $Env:CODEBUILD_RESOLVED_SOURCE_VERSION

artifacts:
  files:
    - target/*.jar
  discard-paths: yes
  name: $Env:APP_NAME-
