version: 0.2
# wolfgang unger 4.2018 - code project with java image - install docker 
phases:
  install:
    commands:
     # variables
      #- REPOSITORY_URI=repository  
      #- ARTIFACT=spring-boot
      #- ARTIFACT_TYPE=.jar 
      #- TAG_NAME=$REPOSITORY_URI:$ARTIFACT
      #- echo $AWS_DEFAULT_REGION 
      #- echo $ARTIFACT
      #- echo $ARTIFACT_TYPE
      #- echo $REPOSITORY_URI
      #- echo $TAG_NAME  
      # installation
      - apt-get update -y
      - apt-get install -y software-properties-common
      #- apt-get install -y openjdk-11-jdk-headless
      - apt-get install -y default-jdk
      - apt-get install -y maven
      - apt-get install -y gradle

  pre_build:
    commands:

  build:
    commands:
      - echo Maven Build ...
      - if [ -e spring-petclinic ]; then cd spring-petclinic; fi
      - mvn package
      #- java -jar target/*.jar

artifacts:
  files:
    - target/*.jar
  discard-paths: yes
